### ISSUE TITLE
End Condition

### ISSUE THREAD

**Issue by ImperialOfficer324** [ImperialOfficer324/CollabGame#44]
## When the first player reaches the gate...
**Some Ideas**:
+ Only one level is loaded and when the first player completes it they are crowned the winner and the game ends (I'm leaning towards this one)
+ the first level is loaded and then players continue through all levels alphabetically and the first player to finish all levels wins (this one is complicated and doesn't seem as fun)
+ When loading the server, a selection of levels are selected and the players play through them in the order selected.

**Again, I'm leaning towards the first one. What do you think?**

**Comment by TheBigH11** [comment]
I did some testing of the two routes to the end for the first level. With no mistakes or interference, they both took about 10 seconds to complete. This might mean that games will be pretty short if there was only one level, but that is not necessarily bad.

**Comment by ImperialOfficer324** [comment]
Yes, but I was actually thinking we would make larger maps so they took longer. (of course, we have to be reasonable, we're only working with laptops and python)

**Comment by ImperialOfficer324** [comment]
Added a simple end screen
