### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by ImperialOfficer324** [ImperialOfficer324/CollabGame#48]
I think there should be no death among slimes.
I think each slime should have 2 attacks:
+ Punch (knocks other slime back)
+ Freeze (freezes the other slime for a certain amount of time)

**Comment by TheBigH11** [comment]
Added a freeze effect without visuals

**Comment by TheBigH11** [comment]
Added a punch attack without visuals

**Comment by TheBigH11** [comment]
Only need visual affects

**Comment by ImperialOfficer324** [comment]
Added visual Effects for freeze
Only need vfx for the punch
