### ISSUE TITLE
Maybe move client code to server

### ISSUE THREAD

**Issue by TheBigH11** [ImperialOfficer324/CollabGame#69]
If the client code was in the server instead, and the clients were pretty much just displaying, it would be a lot harder to "hack", and would provide an identical experience to both players; currently either player can modify their own  freeze duration, speed, gravity, friction, etc.

**Comment by ImperialOfficer324** [comment]
This is a good point, but it is WAY too advanced for what we're trying to do. This would basically require rewriting the entire game, and I'm not really inspired to do that.

**Comment by TheBigH11** [comment]
There is are advantages to both, and it would require a lot of modification, also works pretty well as is :)
